force-app/main/default/objects/Cash_Book__c/Cash_Book__c.object-meta.xml
<CustomObject>
    <label>Cash Book</label>
    <nameField>
        <label>Cash Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Book__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CashBookController.cls
public class CashBookController 
{
	@AuraEnabled
    public static List<Cash_Book__c> getAllCashBooks()
    {
        List<Cash_Book__c> cashBooks = [SELECT Id, Name, Total_Amount__c FROM Cash_Book__c];
        return cashBooks;
    }
    @AuraEnabled
    public static String createNewCashBook(String Name)
    {
        try 
        {
            Cash_Book__c cashbook = new Cash_Book__c(Name=Name);
            Database.SaveResult sr = Database.insert(cashbook, false);
            if (sr.isSuccess()) 
            {
                return 'Success Cash_Book__c Record Inserted: ' + sr.getId();
            } else 
            {
                String errors = '';
                for (Database.Error err : sr.getErrors()) 
                {
                    errors += err.getMessage() + ' ';
                }
                return errors;
            }
        } catch (Exception e) 
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
}